### ISSUE TITLE
Broken 1098 OTB compilation

### ISSUE THREAD

**Issue by Humberd** [Arch-Mina/Assets-Editor#24]
When I compile a dat file and then try to open it again it throws the following error:

```log
Unhandled exception. System.Exception: Couldn't load dat file
   at Assets_Editor.LegacyAppearance.ReadLegacyDat(String file) in D:\Repositories\Asset-Editor\Assets Editor\LegacyAppearance.cs:line 117
   at Assets_Editor.MainWindow.LoadLegacyDat() in D:\Repositories\Asset-Editor\Assets Editor\MainWindow.xaml.cs:line 116
   at Assets_Editor.MainWindow.SelectAssetsFolder(Object sender, RoutedEventArgs e) in D:\Repositories\Asset-Editor\Assets Editor\MainWindow.xaml.cs:line 171
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
```

Reproduction Steps:
1. Open 1098 dat file
2. Compile it
3. Open the new compiled dat file

Expected result:
Reads a compiled file

Actual result:
Throws an error and closes the program.

Original dat file: [Tibia.dat](https://github.com/Arch-Mina/Assets-Editor/files/14460445/Tibia.zip)
Compiled dat file: [Tibia-generated.dat](https://github.com/Arch-Mina/Assets-Editor/files/14460475/Tibia-generated.zip)

**Comment by Arch-Mina** [comment]
The editor is not compatible with ISO-8859-1 encoding, which is only used for item ID 8015, "Jalapeño Pepper", in more recent clients it's named "Jalapeno Pepper"
Renaming this item should fix your issue.

**Comment by Humberd** [comment]
I removed the problematic character, but the issue remains the same.

[Tibia-generated2.zip](https://github.com/Arch-Mina/Assets-Editor/files/14462520/Tibia-generated2.zip)
